// auto generated by jp.co.worksap.jax_rs.ApiScriptGenerator
define(['jquery', 'exports'], function($, exports) {
  'use strict';
  var baseURL = $('meta[name="app-data"]').data('context-path') + '/resources';
  exports.load = function (message) {
    return $.ajax({
        cache: false,
        url: baseURL + '/sample/',
        type: 'get',
        data: {'message':message}
    }).promise();
  };
  exports.postCat = function (foo,bar) {
    return $.ajax({
        cache: false,
        url: baseURL + '/sample/cat',
        type: 'post',
        data: {'foo':foo,'bar':bar}
    }).promise();
  };
  exports.callDog = function (name) {
    return $.ajax({
        cache: false,
        url: baseURL + '/sample/dog/' + encodeURI(name),
        type: 'put',
        data: {}
    }).promise();
  };
});